import type { Metadata } from "next";

import "./globals.css";
import { NavBar } from "../../components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar />
      <body className="bg-[#ededed] min-h-screen w-full px-2 sm:px-6 md:px-10">
        <div className="w-full flex flex-col items-center mx-auto">
          <div className="md:hidden w-full flex flex-col flex-end items-end mr-4 ">
            <p className="text-xs font-light tracking-wide text-[color-brand]">
              The Best American Materials & Great Prices
            </p>
            <a
              href="tel:540-255-8494"
              className=" text-lg font-light tracking-wider text-second"
            >
              540-255-8494
            </a>
          </div>

          <div className="relative w-full hidden md:block mt-4">
            <img
              src="/images/cover.jpg"
              alt="Cover"
              className="w-full object-cover object-center h-auto max-h-[80vh] sm:max-h-screen"
            />
          </div>

          <div className="flex flex-col items-center justify-center mx-auto w-full">
            <div>{children}</div>
          </div>
        </div>
      </body>

      <footer className="flex justify-center items-center py-6 text-center gap-1.5 mx-auto w-full max-w-[820px] text-sm sm:text-sm font-light  text-[color-brand]">
        &copy; {new Date().getFullYear()} GLR Solution <p>|</p>
        <a
          href="https://www.instagram.com/glr_solution/"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-2 underline"
        >
          Instagram
        </a>{" "}
        <p>|</p>
        <a
          href="https://www.instagram.com/glr_solution/"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-2 underline"
        >
          Facebook
        </a>
      </footer>
    </html>
  );
}
