import type { Metadata } from "next";

import "./globals.css";
import { NavBar } from "../../components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar />
      <body className="bg-[#ededed] min-h-screen w-full m- pl-10 pr-10">
        <div className="w-full flex flex-col items-center mx-auto">
          <div className="relative w-full">
            <img
              src="/images/cover.jpg"
              alt="Cover"
              className="w-full object-contain object-top h-auto max-h-screen"
            />
          </div>

          <div className="flex flex-col items-center justify-center mx-auto w-full">
            <div>{children}</div>
          </div>
        </div>
      </body>

      <footer className="flex justify-center items-center py-6 text-center gap-1.5 mx-auto w-full max-w-[820px]">
        &copy; {new Date().getFullYear()} LLC <p>|</p>
        <a
          href="https://www.instagram.com/glr_solution/"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-2 underline"
        >
          Instagram
        </a>{" "}
        <p>|</p>
        <a
          href="https://www.instagram.com/glr_solution/"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-2 underline"
        >
          Facebook
        </a>
      </footer>
    </html>
  );
}
